### ISSUE TITLE
Add possibility to not force refocusing on Code

### ISSUE THREAD

**Issue by godbout** [fabiospampinato/vscode-browser-refresh#1]
Just some thoughts. Your extension is fantastic when using 2 or more screens, but is not convenient when using only one screen (usually with apps in fullscreen mode). So it'd be great to have a setting to let users decide if they want the focus to be set back to Code or kept on the browser.

I can check out your code and do a PR if needed.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, I'll work on this in the following days.

**Comment by fabiospampinato** [comment]
Fixed in v1.1.1.

**Comment by godbout** [comment]
Thank you @fabiospampinato!
