### ISSUE TITLE
Cmd-R no longer working

### ISSUE THREAD

**Issue by theDanielJLewis** [fabiospampinato/vscode-browser-refresh#10]
I can't figure this out, but my browser will no longer refresh when I press Cmd-R. That keyboard shortcut is properly assigned and has no other global conflicts. My browser is properly entered. Running Browser: Refresh from the command palette works, but not Cmd-R.

When I try it, I see VS Code says in its footer, "Cmd-R was pressed. Waiting for second key of chord..."

I'm on macOS 14.2.1 with VS Code 1.85.2.

It's been like this for a while. So maybe it was a VS Code update?

I thought maybe it was my browser, because it seemed to work with Chrome and Brave, but not with Arc—at least a week ago. Now, though, I can't get Cmd-R to work with Chrome or Brave at all!

**Comment by fabiospampinato** [comment]
It may be worth reporting this issue upstream, it's not strictly a problem that the extension itself can solve. I was going to guess that maybe some other extension is contributing a shortcut that takes precedence over ours, but it seems incompatible with you seeing "Cmd-R was pressed...".

You could try explicitly setting a shortcut for this in the settings:

```json
{ "key": "cmd+r", "command": "browserRefresh.refresh" }
```

**Comment by theDanielJLewis** [comment]
SOLVED! It's a conflict with the Postman extension!

While I was trying to figure out where to put that key command code you gave me, I found "Toggle keyboard shortcuts troubleshooting" in the command bar. I enabled that, hit Cmd-R, and watched the log:

```
2024-03-08 14:20:22.190 [info] [KeybindingService]: | Resolving meta+[KeyR]
2024-03-08 14:20:22.190 [info] [KeybindingService]: \ From 6 keybinding entries, awaiting 1 more chord(s), when: postman-for-vscode:sign-in, source: user extension Postman.postman-for-vscode.
2024-03-08 14:20:22.190 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyR, keyCode: 82, key: r
2024-03-08 14:20:22.190 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyR, keyCode: 48 ('R')
```

Although I don't quite know what that log is showing, I could clearly see Postman referenced in there, so I tried disabling it and now Cmd-R works again!

I know your solution didn't actually fix the problem, but it helped lead to the solution. So thank you!
