### ISSUE TITLE
2.0.0 and 2.0.1 stopped activate chrome on command-R

### ISSUE THREAD

**Issue by nesterscript** [fabiospampinato/vscode-browser-refresh#12]
MacBook Pro
14-inch, 2021, 16 GB
Apple M1 Pro 
macOs 14.3.1

Browser Refresh: Focus - checked in settings.

On version 2.x.x it does not activate chrome anymore and stay in VSCode.
Downgraded back to 1.2.0

**Comment by fabiospampinato** [comment]
It should be fixed in v2.0.2, thank you 👍

**Comment by nesterscript** [comment]
Confirmed - all good in 2.0.2 😊
