### ISSUE TITLE
Running the contributed command: 'browserRefresh.refresh' failed.

### ISSUE THREAD

**Issue by martinandersen3d** [fabiospampinato/vscode-browser-refresh#2]
I get the error
`Running the contributed command: 'browserRefresh.refresh' failed.`

How can I fix?

With chrome :-)

**Comment by fabiospampinato** [comment]
Is there any stack trace in the debug pane?

**Comment by martinandersen3d** [comment]
![image](https://user-images.githubusercontent.com/19984581/58383892-0ed6c680-7fdc-11e9-94d6-2f992414210f.png)

**Comment by fabiospampinato** [comment]
That's the devtools, not the debug pane:

<img width="864" alt="Screen Shot 2019-05-26 at 17 32 43" src="https://user-images.githubusercontent.com/1812093/58383925-48a7cd00-7fdc-11e9-95ce-491c01047b31.png">

**Comment by martinandersen3d** [comment]
there is no errors there

but is this related? (windows 10, vscode stabel release)

![image](https://user-images.githubusercontent.com/19984581/58383966-958ba380-7fdc-11e9-814a-0f3f861693c0.png)

**Comment by fabiospampinato** [comment]
Probably, this module only works on macOS and uses `osascript`, which you can't use under Win10.
