### ISSUE TITLE
Do not rely on keycodes for browsers that can be reloaded by a specific call

### ISSUE THREAD

**Issue by EugeneDae** [fabiospampinato/vscode-browser-refresh#4]
A much cleaner way to reload a current tab for Chrome, Edge, Opera and Safari:

```
tell application "Google Chrome"
	reload active tab of front window
end tell

tell application "Microsoft Edge"
	reload active tab of front window
end tell

tell application "Opera"
	reload active tab of front window
end tell

tell application "Safari"
	set URL of current tab of front window to (URL of current tab of front window)
end tell
```

AFAIK Firefox can only be reloaded by keycodes.

With keycodes VSCode still loses focus for half a second and this is ugly.

**Comment by fabiospampinato** [comment]
Sounds like a good idea. 

PRs welcome for avoiding the focus switch as much as possible.

**Comment by EugeneDae** [comment]
I've never dealt with TypeScript and I'm new to VSCode. Can you implement this? I'm all yours if you need assistance with AppleScript.

**Comment by fabiospampinato** [comment]
Right now I don't have time to work on this unfortunately, however it shouldn't take long to implement, if you have applescripts for hard reloading those browsers too I can probably find the time for this.

**Comment by EugeneDae** [comment]
The AppleScripts above are all functional. There needs to be a conditional check for browser name, something like this:

```
if (browser == "Google Chrome" || browser == "Microsoft Edge" || browser == "Opera") {
  // Chromium-based browsers
  const refreshScript = 'tell application "${browser}" to reload active tab of front window'
} else if (browser == "Safari") {
  // Safari
  const refreshScript = 'tell application "${browser}" to set URL of current tab of front window to (URL of current tab of front window)'
} else {
  const refreshScript = `
    tell application "${browser}" to activate
    tell application "System Events"
      delay ${delay}
      key code 15 using {command down ${ force ? ', shift down' : '' }} # ⌘R/⇧⌘R
    end tell
    ${ focus ? '' : `tell application "${app}" to activate` }
  `;
}

applescript.execString(refreshScript);
```

**Comment by fabiospampinato** [comment]
I was talking about **hard** reloading too.

**Comment by EugeneDae** [comment]
Ah, sorry, missed it. I'm afraid hard reloading is not possible without keycodes. Personally I never needed hard reloading, because I always keep browser console open.

**Comment by EugeneDae** [comment]
I've hacked together another extension called [Refresh Browser](https://github.com/EugeneDae/vscode-refresh-browser) (sorry, I'm bad at naming).

It communicates with browsers directly via their AppleScript API only, for this reason:

1. It doesn't support Firefox, Tor Browser etc.
2. It can't send a force refresh command.
3. BUT! you can configure it to refresh a specific tab — for example, the tab whose URL starts with `https://localhost` or `https://local`.

In the README I recommend users who need (1) or/and (2) to install this extension instead.

TypeScript was kinda fun, everything else was pain (especially initial configuration). Having experienced the process, I respect your work for the VS Code ecosystem even more @fabiospampinato. You're a great person, thank you. I will give your Markdown app a go soon.

Perhaps this issue can be closed.

**Comment by fabiospampinato** [comment]
I'm reopening as I'd like to implement that in this extension as well 👍

**Comment by fabiospampinato** [comment]
Implemented.
