### ISSUE TITLE
[NFR] Support for Choosy?

### ISSUE THREAD

**Issue by richmilns** [fabiospampinato/vscode-browser-refresh#6]
I was wondering if it's possible to get this working with [Choosy](https://www.choosyosx.com)?

This might be useful if testing in lots of different browsers.

Choosy has an [API](https://www.choosyosx.com/api) which supports AppleScript as well.

**Comment by fabiospampinato** [comment]
I think you could just open the browser you want and the extension will do the rest. For some deeper integration with that you'll need a dedicated extension for it.
