### ISSUE TITLE
Unexpected AppleScript error occurred while trying to refresh browser. 

### ISSUE THREAD

**Issue by mikaeylinen** [fabiospampinato/vscode-browser-refresh#7]
Unexpected AppleScript error occurred while trying to refresh browser. Please report to https://git.io/Ju4oG. Error: 270:273: syntax error: Expected end of line, etc. but found property. (-2741)

Running MacOS 12

**Comment by Grabowski-GDS** [comment]
I have same problem ;( Waiting for support

**Comment by fabiospampinato** [comment]
It's working for me on macOS 12 🤔  Which browsers are you folks using?

**Comment by Grabowski-GDS** [comment]
> It's working for me on macOS 12 🤔 Which browsers are you folks using?
today i updated my 11.4 macos to 12 and it started to work. Thanks buddy

**Comment by fabiospampinato** [comment]
Closing as it seems this started working again. Feel free to provide more info (like macos version and extension configuration) to reopen 👍
